[package]
name = "twine-l1-transactions-precompile"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
reth-revm.workspace = true
reth-tracing.workspace = true

alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
alloy-trie.workspace = true

twine-solana-consensus-prover-lib.workspace = true

borsh.workspace = true
eyre.workspace = true
serde_json.workspace = true
thiserror.workspace = true

twine-constants = { workspace = true }
twine-evm-contracts.workspace = true
twine-l1-utils.workspace = true

[lints]
workspace = true
