[package]
name = "twine-sequencer"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
async-trait.workspace = true
clap.workspace = true
eyre.workspace = true
http.workspace = true
jsonrpsee.workspace = true
lazy_static.workspace = true
reth-engine-primitives.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-rpc-api.workspace = true
reth-rpc-layer.workspace = true
serde.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
twine-l1-eth.workspace = true
twine-l1-solana.workspace = true

[lints]
workspace = true

# [features]
# default = ["sequencer"]
# sequencer = []
# verifier = []
