[package]
name = "twine-sequencer"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alloy-contract.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-signer-local.workspace = true
alloy-sol-types.workspace = true
async-trait.workspace = true
base64.workspace = true
borsh.workspace = true
celestia-rpc = "0.15.0"
celestia-types = "0.17.0"
chrono.workspace = true
clap.workspace = true
eyre.workspace = true
futures-util.workspace = true
hex.workspace = true
http.workspace = true
jsonrpsee.workspace = true
lazy_static.workspace = true
reqwest = { workspace = true, features = ["json"] }
reth-engine-primitives.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-rpc-api.workspace = true
reth-rpc-layer.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true
tendermint = "0.39.0"
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
twine-evm-contracts.workspace = true
twine-l1-eth.workspace = true
twine-l1-solana.workspace = true
twine-sequencer-db.workspace = true
# ctrlc-async.workspace = true

[lints]
workspace = true

[features]
default = ["sequencer", "verifier"]
sequencer = []
verifier = []
