[package]
name = "twine-merkora-db-poller"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
twine-db.workspace = true
twine-merkora-ethereum.workspace = true
twine-merkora-solana.workspace = true
twine-merkora-types.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = []
zkmode = []
