[package]
name = "merkora-db-poller"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
merkora-db.workspace = true
merkora-ethereum.workspace = true
merkora-solana.workspace = true
merkora-types.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = []
zkmode = []
