[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
repository = "https://github.com/twinexyz/weaver"
exclude = [".github/"]

[workspace]
members = [
    "bin/node",
    "bin/devtest",

    "crates/executor",
    "crates/constants",
    "crates/precompiles/consensus-verifier", 
    "crates/precompiles/transaction", 
    "crates/evm-contracts",
]
resolver = "3"

[workspace.dependencies]
alloy-primitives = { version = "0.8.15", default-features = false}
alloy-consensus = { version = "0.11.1", default-features = false }
alloy-genesis = { version = "0.11.1", default-features = false }
# alloy-evm = { version = "0.1.0-alpha.3", default-features = false }
alloy-contract = { version = "0.11.1", default-features = false }
alloy-sol-types = { version = "0.8.20", features = ["json"] }
eyre = "0.6"
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
ssz_types = "0.7.0"
thiserror = "2.0.12"
parking_lot = "0.12"
regex = "1.11.1"
log = "0.4.26"
env_logger = "0.11.7"
git2 = "0.20.1"

# RETH
reth = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-exex = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2", features = [
  "test-utils",
] }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-ethereum-payload-builder = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-evm = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2" }
reth-revm = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2", default-features = false, features = [
  "std",
] }
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.2.2", default-features = false, features = [
  "alloy-compat",
  "std",
] }

twine-executor = { path = "crates/executor" }
twine-consensus-verifier-precompile = { path = "crates/precompiles/consensus-verifier" }
twine-transaction-precompile = { path = "crates/precompiles/transaction" }
twine-evm-contracts = { path = "crates/evm-contracts" }
twine-constants = { path = "crates/constants" }

[patch.crates-io]
# The following is required since we would like to remove
# unnecessary dependency on `ring` crate which original
# `ethereum_hashing` crate depended on.
# ethereum_hashing = { git = "https://github.com/Atamanov/ethereum_hashing.git" }
# Below is heavily inspired from codebases like `reth`. We find the following
# to be quite helpful.

[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rustdoc.all = "warn"

[workspace.lints.clippy]
# These are some of clippy's nursery (i.e., experimental) lints that we like.
# By default, nursery lints are allowed. Some of the lints below have made good
# suggestions which we fixed. The others didn't have any findings, so we can
# assume they don't have that many false positives. Let's enable them to
# prevent future problems.
borrow_as_ptr = "warn"
branches_sharing_code = "warn"
clear_with_drain = "warn"
cloned_instead_of_copied = "warn"
collection_is_never_read = "warn"
dbg_macro = "warn"
derive_partial_eq_without_eq = "warn"
doc_markdown = "warn"
empty_line_after_doc_comments = "warn"
empty_line_after_outer_attr = "warn"
enum_glob_use = "warn"
equatable_if_let = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
flat_map_option = "warn"
from_iter_instead_of_collect = "warn"
if_not_else = "warn"
if_then_some_else_none = "warn"
implicit_clone = "warn"
imprecise_flops = "warn"
iter_on_empty_collections = "warn"
iter_on_single_items = "warn"
iter_with_drain = "warn"
iter_without_into_iter = "warn"
large_stack_frames = "warn"
manual_assert = "warn"
manual_clamp = "warn"
manual_is_variant_and = "warn"
manual_string_new = "warn"
match_same_arms = "warn"
missing-const-for-fn = "allow" # TODO: https://github.com/rust-lang/rust-clippy/issues/14020
mutex_integer = "warn"
naive_bytecount = "warn"
needless_bitwise_bool = "warn"
needless_continue = "warn"
needless_for_each = "warn"
needless_pass_by_ref_mut = "warn"
nonstandard_macro_braces = "warn"
option_as_ref_cloned = "warn"
or_fun_call = "warn"
path_buf_push_overwrite = "warn"
read_zero_byte_vec = "warn"
result_large_err = "allow"
redundant_clone = "warn"
redundant_else = "warn"
single_char_pattern = "warn"
string_lit_as_bytes = "warn"
string_lit_chars_any = "warn"
suboptimal_flops = "warn"
suspicious_operation_groupings = "warn"
trailing_empty_array = "warn"
trait_duplication_in_bounds = "warn"
transmute_undefined_repr = "warn"
trivial_regex = "warn"
tuple_array_conversions = "warn"
type_repetition_in_bounds = "warn"
uninhabited_references = "warn"
unnecessary_self_imports = "warn"
unnecessary_struct_initialization = "warn"
unnested_or_patterns = "warn"
unused_peekable = "warn"
unused_rounding = "warn"
use_self = "warn"
useless_let_if_seq = "warn"
while_float = "warn"
zero_sized_map_values = "warn"

# These are nursery lints which have findings. Allow them for now. Some are not
# quite mature enough for use in our codebase and some we don't really want.
# Explicitly listing should make it easier to fix in the future.
as_ptr_cast_mut = "allow"
cognitive_complexity = "allow"
debug_assert_with_mut_call = "allow"
fallible_impl_from = "allow"
future_not_send = "allow"
needless_collect = "allow"
non_send_fields_in_send_ty = "allow"
redundant_pub_crate = "allow"
significant_drop_in_scrutinee = "allow"
significant_drop_tightening = "allow"
too_long_first_doc_paragraph = "allow"

# Speed up compilation time for dev builds by reducing emitted debug info.
# NOTE: Debuggers may provide less useful information with this setting.
# Uncomment this section if you're using a debugger.
[profile.dev]
# https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
codegen-units = 16
