[workspace.package]
version = "0.1.0"
edition = "2021"
exclude = [".github/"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/twinexyz/weaver"
rust-version = "1.85"

[workspace]
members = [
  "bin/aggregator",
  "bin/devtest",
  "bin/node",
  "crates/aggregator/common",
  "crates/aggregator/database",
  "crates/aggregator/dispatcher",
  "crates/aggregator/metrics",
  "crates/aggregator/types",
  "crates/constants",
  "crates/db/batch",
  "crates/ethereum-consensus-prover",
  "crates/evm-contracts",
  "crates/executor",
  "crates/exex",
  "crates/integration-tests",
  "crates/kafka",
  "crates/kafka/common",
  "crates/kafka/consumer",
  "crates/kafka/producer",
  "crates/l1-utils",
  "crates/l2-batch-poller",
  "crates/precompiles/l1-consensus-verifier",
  "crates/precompiles/l1-transactions",
  "crates/precompiles/zstd",
  "crates/rpc",
  "crates/solana-consensus-prover",
  "crates/solana-sdk",
  "crates/test-harness",
  "crates/types",
  "crates/utils",
]
resolver = "3"

[workspace.dependencies]
# The versions of alloy related crates should be fetched from `reth`
# https://github.com/paradigmxyz/reth/blob/{RETH_TAG}/Cargo.toml
alloy-consensus = { version = "0.14.0", default-features = false }
alloy-contract = { version = "0.14.0", default-features = false }
# needed to implement `encode_2718` function which comes from `use alloy_eips::Encodable2718;`
alloy-eips = { version = "0.14.0", default-features = false }
alloy-genesis = { version = "0.14.0", default-features = false }
alloy-primitives = { version = "1.0.0", default-features = false, features = ["map-foldhash", "serde"] }
alloy-rpc-types = { version = "0.14.0", features = ["eth"], default-features = false }
alloy-sol-types = { version = "1.0.0", default-features = false, features = ["json"] }
alloy-trie = { version = "0.8.1", default-features = false }

bls12_381 = { git = "https://github.com/sp1-patches/bls12_381", branch = "n/release-latest", features = ["experimental"], package = "sp1_bls12_381" }

clap = { version = "4.5.46", features = ["derive"] }
env_logger = "0.11.7"
ethereum_ssz = "0.9.0"
ethereum_ssz_derive = "0.9.0"
eyre = "0.6"
futures-util = "0.3"
git2 = "0.20.1"
hex = "0.4.3"
jsonrpsee = { version = "0.24", features = ["client", "jsonrpsee-proc-macros", "tracing", "server"] }
log = "0.4.26"
once_cell = "1.19.0"
parking_lot = "0.12"
prometheus = "0.14.0"
rand = "0.8.5"
regex = "1.11.1"
reqwest = { version = "0.11", features = ["json"] }
rocksdb = "0.23.0"
ruzstd = "0.8.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_bytes = "0.11.14"
serde_json = "1.0.132"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-async-std-native-tls", "chrono"] }
ssz_types = "0.11.0"
thiserror = "2.0.12"
tiny_http = "0.12"
tokio = { version = "1.40.0", features = ["full"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
tree_hash = "0.10.0"
tree_hash_derive = "0.10.0"
typenum = "1.12.0"

# SOLANA
bincode = "1.3"
blake3 = { git = "https://github.com/twinexyz/BLAKE3" }
borsh = { version = "1.2.1", features = ["derive", "unstable__schema"] }
borsh0_10 = { package = "borsh", version = "0.10.3" }
borsh0_9 = { package = "borsh", version = "0.9.3" }
bs58 = "0.4.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
num-derive = "0.4"
num-traits = { version = "0.2", features = ["i128"] }
sha2_solana = { package = "sha2", git = "https://github.com/sp1-patches/RustCrypto-hashes", tag = "patch-0.10.8-sp1-4.0.0-rc.3" }
smallvec = "1.13.2"
solana-short-vec = "2.2.1"
tempfile = "3.10"

solana-consensus-prover-lib = { git = "ssh://git@github.com/twinexyz/solana-consensus-prover" }

# RETH
reth = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-ethereum-payload-builder = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-evm = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-exex = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-node-core = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10", features = ["test-utils"] }
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10", default-features = false, features = ["alloy-compat", "std"] }
reth-provider = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10", default-features = false }
reth-revm = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10", default-features = false, features = ["std"] }
reth-tracing = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.3.10" }
reth-trie-common = { git = "https://github.com/paradigmxyz/reth", tag = "v1.3.10", default-features = false, features = ["eip1186", "serde"] }

revm-context = { version = "3.0.0", default-features = false }

test-harness = { path = "crates/test-harness" }
twine-aggregator-common = { path = "crates/aggregator/common" }
twine-aggregator-database = { path = "crates/aggregator/database" }
twine-aggregator-metrics = { path = "crates/aggregator/metrics" }
twine-constants = { path = "crates/constants" }
twine-db-batch = { path = "crates/db/batch" }
twine-ethereum-consensus-prover-lib = { path = "crates/ethereum-consensus-prover" }
twine-evm-contracts = { path = "crates/evm-contracts" }
twine-executor = { path = "crates/executor" }
twine-exex = { path = "crates/exex" }
twine-integration-tests = { path = "crates/integration-tests" }
twine-l1-consensus-verifier-precompile = { path = "crates/precompiles/l1-consensus-verifier" }
twine-l1-transactions-precompile = { path = "crates/precompiles/l1-transactions" }
twine-l1-utils = { path = "crates/l1-utils" }
twine-l2-batch-poller = { path = "crates/l2-batch-poller" }
twine-rpc = { path = "crates/rpc" }
twine-solana-consensus-prover-lib = { path = "crates/solana-consensus-prover" }
twine-solana-sdk = { path = "crates/solana-sdk" }
twine-types = { path = "crates/types" }
twine-utils = { path = "crates/utils" }
twine-zstd-precompile = { path = "crates/precompiles/zstd" }

[patch.crates-io]
# The following is required since we would like to remove
# unnecessary dependency on `ring` crate which original
# `ethereum_hashing` crate depended on.
ethereum_hashing = { git = "https://github.com/Atamanov/ethereum_hashing.git" }
# Below is heavily inspired from codebases like `reth`. We find the following
# to be quite helpful.

[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.rust_2018_idioms = { level = "deny", priority = -1 }
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rustdoc.all = "warn"

[workspace.lints.clippy]
# These are some of clippy's nursery (i.e., experimental) lints that we like.
# By default, nursery lints are allowed. Some of the lints below have made good
# suggestions which we fixed. The others didn't have any findings, so we can
# assume they don't have that many false positives. Let's enable them to
# prevent future problems.
borrow_as_ptr = "warn"
branches_sharing_code = "warn"
clear_with_drain = "warn"
cloned_instead_of_copied = "warn"
collection_is_never_read = "warn"
dbg_macro = "warn"
derive_partial_eq_without_eq = "warn"
doc_markdown = "warn"
empty_line_after_doc_comments = "warn"
empty_line_after_outer_attr = "warn"
enum_glob_use = "warn"
equatable_if_let = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
flat_map_option = "warn"
from_iter_instead_of_collect = "warn"
if_not_else = "warn"
if_then_some_else_none = "warn"
implicit_clone = "warn"
imprecise_flops = "warn"
iter_on_empty_collections = "warn"
iter_on_single_items = "warn"
iter_with_drain = "warn"
iter_without_into_iter = "warn"
large_stack_frames = "warn"
manual_assert = "warn"
manual_clamp = "warn"
manual_is_variant_and = "warn"
manual_string_new = "warn"
match_same_arms = "warn"
missing-const-for-fn = "allow" # TODO: https://github.com/rust-lang/rust-clippy/issues/14020
mutex_integer = "warn"
naive_bytecount = "warn"
needless_bitwise_bool = "warn"
needless_continue = "warn"
needless_for_each = "warn"
needless_pass_by_ref_mut = "warn"
nonstandard_macro_braces = "warn"
option_as_ref_cloned = "warn"
or_fun_call = "warn"
path_buf_push_overwrite = "warn"
read_zero_byte_vec = "warn"
result_large_err = "allow"
redundant_clone = "warn"
redundant_else = "warn"
single_char_pattern = "warn"
string_lit_as_bytes = "warn"
string_lit_chars_any = "warn"
suboptimal_flops = "warn"
suspicious_operation_groupings = "warn"
trailing_empty_array = "warn"
trait_duplication_in_bounds = "warn"
transmute_undefined_repr = "warn"
trivial_regex = "warn"
tuple_array_conversions = "warn"
type_repetition_in_bounds = "warn"
uninhabited_references = "warn"
unnecessary_self_imports = "warn"
unnecessary_struct_initialization = "warn"
unnested_or_patterns = "warn"
unused_peekable = "warn"
unused_rounding = "warn"
use_self = "warn"
useless_let_if_seq = "warn"
while_float = "warn"
zero_sized_map_values = "warn"

# These are nursery lints which have findings. Allow them for now. Some are not
# quite mature enough for use in our codebase and some we don't really want.
# Explicitly listing should make it easier to fix in the future.
as_ptr_cast_mut = "allow"
cognitive_complexity = "allow"
debug_assert_with_mut_call = "allow"
fallible_impl_from = "allow"
future_not_send = "allow"
needless_collect = "allow"
non_send_fields_in_send_ty = "allow"
redundant_pub_crate = "allow"
significant_drop_in_scrutinee = "allow"
significant_drop_tightening = "allow"
too_long_first_doc_paragraph = "allow"

# Speed up compilation time for dev builds by reducing emitted debug info.
# NOTE: Debuggers may provide less useful information with this setting.
# Uncomment this section if you're using a debugger.
[profile.dev]
# https://davidlattimore.github.io/posts/2024/02/04/speeding-up-the-rust-edit-build-run-cycle.html
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
codegen-units = 16
