[package]
name = "twine-twine"
version.workspace = true
edition.workspace = true

[dependencies]
twine-db.workspace = true
twine-ethereum-utils.workspace = true
twine-types.workspace = true

alloy-contract.workspace = true
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-network-primitives.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-signer-local.workspace = true
alloy-sol-macro.workspace = true
alloy-sol-types.workspace = true
alloy-transport-http.workspace = true
eyre.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
