# Replace with your local genesis JSON
genesis_path: /home/nobel/dev/weaver/bin/node/res/dev-genesis.json

# Postgres database connection string
# Format: postgresql://<user>:<password>@<host>:<port>/<db>?sslmode=require
database_path: postgresql://nobel:nobel@localhost:5432/merkora

# Path to your Solidity contracts directory
contracts_path: /home/nobel/dev/twine-solidity-contracts

# Paths to required binaries (ensure they are in your $PATH or specify full paths)
merkora_binary: /home/nobel/dev/merkora/merkora
twine_node_binary: /home/nobel/dev/weaver/target/release/twine-node
ethereum_binary: /home/nobel/.cargo/bin/reth

# Solana test validator binary
solana_binary: /home/nobel/.local/share/solana/install/releases/stable-72664e237c182faaff0fadfb6b15ba1ee4918e20/solana-release/bin/solana-test-validator 

# Geyser plugin configuration for Solana
geyser_config: /home/nobel/dev/solana-geyser/config.json 

# Directory containing your Solana programs
# solana_program_path: /home/nobel/dev/twine-native-solana-programs
solana_program_path: /tmp/twine-native-solana-programs

# Solana consensus prover binary
solana_consensus_prover: /home/nobel/dev/twine-consensus-prover/target/release/twine-consensus-prover