[package]
name = "merkora-ethereum"
version.workspace = true
edition.workspace = true

[dependencies]
merkora-config.workspace = true
merkora-types.workspace = true
twine-evm-contracts.workspace = true
twine_tcp_lib.workspace = true

alloy = { version = "0.5.4", features = ["full"] }
alloy-primitives = "0.8.10"
alloy-rlp = { version = "0.3.10", default-features = false }
alloy-sol-types = "0.8.15"
alloy-trie = "0.7.3"

anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true

ethereum_ssz = "0.6.0"
ethereum_ssz_derive = "0.6.0"
reqwest = "0.12.9"
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", rev = "1ce067b77bd5a1c2ec7a03c0bdde363afc602bcc" }
ssz_types = "0.7.0"

futures-util = "0.3.31"
lru = "0.13.0"

[features]
event_websocket = []
block_websocket = []
polling = []
