[package]
name = "twine-merkora-json-rpc-server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
jsonrpsee = { version = "0.24.4", features = ["http-client", "jsonrpsee-proc-macros", "server", "tracing"] }
twine-merkora-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
