[package]
name = "twine-solana-sdk"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bincode.workspace = true
blake3.workspace = true
borsh.workspace = true
borsh0_10.workspace = true
borsh0_9.workspace = true
bs58.workspace = true
bytemuck.workspace = true
log.workspace = true
num-derive.workspace = true
num-traits.workspace = true
rand.workspace = true
serde.workspace = true
serde_bytes.workspace = true
sha2_solana.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[target."cfg(not(target_pointer_width = \"64\"))".dependencies.parking_lot]
version = "0.12"

[lints]
workspace = true
