[package]
name = "twine-integration-tests"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
eyre.workspace = true
git2.workspace = true
log.workspace = true
ruzstd.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
test-harness.workspace = true
testcontainers = { version = "0.24.0" }
testcontainers-modules = { version = "0.12.1", features = ["postgres", "blocking"] }

[dev-dependencies]
env_logger = { workspace = true }
git2.workspace = true
tokio.workspace = true

test-harness.workspace = true

[lints]
workspace = true
