[package]
name = "twine-aggregator-dispatcher"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
twine-aggregator-common.workspace = true
twine-aggregator-database.workspace = true
twine-aggregator-metrics.workspace = true
twine-types.workspace = true

async-trait.workspace = true
eyre.workspace = true
reth-tracing.workspace = true
sqlx.workspace = true
tokio.workspace = true

[lints]
workspace = true
