[solana_emitter]
db_conn_string = "postgres://postgres:postgres@localhost:5432/merkora"
next_message_nonce = 1
solana_rpc = "http://127.0.0.1:8900"
chain_id = 900
next_transform_request_id = 0

[consumer]
kafka_broker_url = "localhost:9092"
kafka_topics = "demo"
kafka_groups = "my-group"
auto_offset_reset = "earliest"
# # optional
# security_protocol = "ssl"
# ssl_ca_location = "ca.crt"
# ssl_certificate_location = "user.crt"
# ssl_key_location = "user.key"

[solana_prover_manager]
prover_binary = "solana-prover-bin"
proof_dir = "solana-proofs"

[attempt]
max_attempts_per_request = 20
max_consume_attempts_per_attempts = 20

[db]
conn_str = "postgres://postgres:postgres@localhost:5432/scheduler"

[processor]
transform_request_channel_size = 100
transform_attempt_channel_size = 100
consume_attempt_channel_size = 100
max_in_process_transform_attempts = 100

[instrumentation]
metrics_server_port = 3000
