[package]
name = "twine-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
reth.workspace = true
reth-chainspec.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-primitives.workspace = true
reth-node-ethereum = { workspace = true, features = ["test-utils"] }
reth-tracing.workspace = true
reth-evm.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
eyre.workspace = true
parking_lot.workspace = true
tokio.workspace = true
twine-consensus-verifier-precompile = { workspace = true, optional = true }
twine-constants = { workspace = true }

[features]
default = ["twine-consensus-verifier-precompile", "twine-transactions-precompile"]
twine-consensus-verifier-precompile = ["dep:twine-consensus-verifier-precompile"]
twine-transactions-precompile = []
