[package]
name = "twine-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus.workspace = true
alloy-evm.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true
eyre.workspace = true
parking_lot.workspace = true
reth.workspace = true
reth-chainspec.workspace = true
reth-ethereum = { workspace = true, features = ["test-utils", "node", "evm", "pool"] }
reth-ethereum-payload-builder.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-execution-types.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum = { workspace = true, features = ["test-utils"] }
reth-primitives.workspace = true
reth-tracing.workspace = true
tokio.workspace = true
twine-constants = { workspace = true }
twine-l1-consensus-verifier-precompile = { workspace = true, optional = true }
twine-l1-transactions-precompile = { workspace = true, optional = true, default-features = false }
twine-zstd-precompile = { workspace = true }

[features]
default = [
  "twine-l1-consensus-verifier-precompile",
  "twine-l1-transactions-precompile",
  "twine-zstd-precompile",
  "mainnet",
]
twine-l1-consensus-verifier-precompile = [
  "dep:twine-l1-consensus-verifier-precompile",
]
twine-l1-transactions-precompile = []
twine-zstd-precompile = []

devnet = ["twine-l1-transactions-precompile/devnet"]
testnet = ["twine-l1-transactions-precompile/testnet"]
mainnet = ["twine-l1-transactions-precompile/mainnet"]
