[package]
name = "twine-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus.workspace = true
alloy-evm = { version = "0.20.1", default-features = false }
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types-engine = { version = "1.0", default-features = false }
eyre.workspace = true
parking_lot.workspace = true
reth.workspace = true
reth-chainspec.workspace = true
reth-ethereum = { workspace = true, features = ["test-utils", "node", "evm", "pool"] }
reth-ethereum-payload-builder.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-execution-types.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum = { workspace = true, features = ["test-utils"] }
reth-primitives.workspace = true
reth-tracing.workspace = true
tokio.workspace = true
twine-constants = { workspace = true }
twine-l1-consensus-verifier-precompile = { workspace = true, optional = true }
twine-l1-transactions-precompile = { workspace = true }
twine-zstd-precompile = { workspace = true }

[features]
default = [
  "twine-l1-consensus-verifier-precompile",
  "twine-l1-transactions-precompile",
  "twine-zstd-precompile",
]
twine-l1-consensus-verifier-precompile = [
  "dep:twine-l1-consensus-verifier-precompile",
]
twine-l1-transactions-precompile = []
twine-zstd-precompile = []
