[package]
name = "twine-exex"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alloy-primitives.workspace = true
eyre.workspace = true
futures-util.workspace = true
reth-chainspec.workspace = true
reth-evm.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-tracing.workspace = true
tokio.workspace = true
twine-db-batch.workspace = true

[lints]
workspace = true
