[package]
name = "twine-db-poller"
version.workspace = true
edition.workspace = true

[dependencies]
twine-db.workspace = true
twine-ethereum-utils.workspace = true
twine-solana-utils.workspace = true
twine-types.workspace = true

eyre.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
default = []
zkmode = []
