solana:
  rpc_url: "http://127.0.0.1:8899"
  bridge_contract_address: "JQTqWZGPZMYB6Q1Tvi34abZaYg7xEePgET9iRm9UgfF"
  verified_batch: 0
  chain_id: 900
ethereum:
  rpc_url: "http://127.0.0.1:8545"
  bridge_contract_address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  verified_batch: 0
  chain_id: 17000
l2:
  rpc_url: "http://127.0.0.1:8545"
  head_block: "0xb8a38c7a3369757f147068413ce04106972dfac7149f27061d5b687becbd7e6a"
  fee_recipient: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  auth_rpc_url: "http://127.0.0.1:8551"
  jwt_token_path: "jwt.hex"
  block_time: 2000
extras:
  verifer_channel_buffer_size: 10
db:
  db_path: "/tmp/sequencer-db"
  db_column_family:
    - "BLOCK_PRODUCER"
    - "CHAIN_WATCHER"
    - "CHAIN_STATE_VERIFIER"
