[package]
name = "twine-l1-consensus-verifier-precompile"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
reth-revm.workspace = true
reth-tracing.workspace = true
revm-context.workspace = true
serde.workspace = true
serde_json.workspace = true
ssz_types.workspace = true
twine-constants.workspace = true
twine-ethereum-consensus-prover-lib.workspace = true
twine-l1-utils.workspace = true
