[package]
name = "twine-l1-consensus-verifier-precompile"
version = "0.1.0"
edition = "2021"

[dependencies]
twine-constants.workspace = true
reth.workspace = true
reth-chainspec.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-primitives.workspace = true
reth-node-ethereum = { workspace = true, features = ["test-utils"] }
reth-tracing.workspace = true
reth-evm.workspace = true
alloy-genesis.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-sol-types.workspace = true
alloy-rlp.workspace = true
eyre.workspace = true
parking_lot.workspace = true
tokio.workspace = true
twine_tcp_lib.workspace = true
twine-solana-sdk.workspace = true
serde_json.workspace = true
serde.workspace = true
borsh.workspace = true
ethereum_ssz.workspace = true
ethereum_ssz_derive.workspace = true
ssz_types.workspace = true
solana-consensus-prover-lib.workspace = true
gkr = { path = "/home/user/Expander/gkr" }
config_macros = { path = "/home/user/Expander/config_macros" }
gkr_engine = { path = "/home/user/Expander/gkr_engine" }
gkr_hashers = { path = "/home/user/Expander/hasher" }
poly_commit = { path = "/home/user/Expander/poly_commit" }
transcript = { path = "/home/user/Expander/transcript" }
mersenne31 = { path = "/home/user/Expander/arith/mersenne31" }

[features]
twine-build =[]
rsp-build = []
