[package]
name = "twine-aggregator-settlement"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
async-trait.workspace = true
borsh.workspace = true
eyre.workspace = true
reth-tracing.workspace = true
solana-sdk.workspace = true
twine-aggregator-common.workspace = true
twine-evm-contracts.workspace = true
twine-l1.workspace = true
twine-l1-eth.workspace = true
twine-l1-solana.workspace = true
twine-types.workspace = true

[lints]
workspace = true
