[package]
name = "twine-json-rpc-server"
version.workspace = true
edition.workspace = true

[dependencies]
twine-merkora-types.workspace = true

anyhow.workspace = true
async-trait.workspace = true
jsonrpsee = { version = "0.24.4", features = ["http-client", "jsonrpsee-proc-macros", "server", "tracing"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
