[package]
name = "twine-aggregator-common"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
eyre.workspace = true
serde.workspace = true
serde_yaml.workspace = true
twine-types.workspace = true

[lints]
workspace = true
