[package]
name = "twine-l2-proof-scheduler"
version.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
log.workspace = true
orchestrator-rs.workspace = true
rdkafka.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
toml.workspace = true
twine-kafka.workspace = true
twine-proof-scheduler-common.workspace = true
twine-rpc.workspace = true
twine-types.workspace = true

[lints]
workspace = true
