name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  fmt-and-udeps:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Add rustfmt (nightly)
      run: rustup component add --toolchain nightly rustfmt
    - name: Cache cargo-udeps
      id: cache-cargo-udeps
      uses: actions/cache@v4
      env:
        cache-name: cache-cargo-udeps
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/bin/cargo-udeps
    - if: ${{ steps.cache-cargo-udeps.outputs.cache-hit != 'true' }}
      name: Install cargo-udeps
      run: cargo install cargo-udeps
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1

  test-harness:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Run http server test
      run: RUST_LOG=info cargo test --package test-harness --lib -- tests::test_start_callapi_stop_python_serve --exact --show-output
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Run anvil test
      run: RUST_LOG=info cargo test --package test-harness --lib -- tests::test_anvil_setup --exact --show-output
