name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  fmt-and-udeps:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Add rustfmt (nightly)
      run: rustup component add --toolchain nightly rustfmt
    - name: Cache cargo-udeps
      id: cache-cargo-udeps
      uses: actions/cache@v4.2.3
      env:
        ACTIONS_RESULTS_URL: ${{ secrets.CACHE_SERVER_URL }}
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/bin/cargo-udeps
        restore-keys: |
          ${{ runner.os }}-cargo-udeps-
    - if: ${{ steps.cache-cargo-udeps.outputs.cache-hit != 'true' }}
      name: Install cargo-udeps
      run: cargo install cargo-udeps --locked --force
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
