name: PipelineTriggerFromTwineSolidityContracts

on:
  repository_dispatch:
    types: [trigger_changes] # Custom event type

env:
  REPO: twine-solidity-contracts
  ORG: ${{ github.repository_owner }}

jobs:
  run_pipeline:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Checkout twine-soladitiy-contracts repo
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ env.ORG }}/${{ env.REPO }}
          path: ${{ env.REPO }}
          token: ${{ secrets.GH_ACTION_PAT  }}
          ref: main

      - name: Run EVM Scripts
        run: |
          cd twine-solidity-contracts
          ./script/updateSp1Version.sh

      - name: Ensure changes are updated
        run: |
          cat twine-solidity-contracts/out/L1MessageQueue.sol/L1MessageQueue.json | jq -r .abi > crates/evm-contracts/res/L1MessageQueue.json
          cat twine-solidity-contracts/out/TwineChain.sol/TwineChain.json | jq -r .abi > crates/evm-contracts/res/TwineChain.json
          cat twine-solidity-contracts/out/L2TwineMessenger.sol/L2TwineMessenger.json | jq -r .abi > crates/evm-contracts/res/L2TwineMessenger.json
          cat twine-solidity-contracts/out/TwineSystemStorageContract.sol/TwineSystemStorageContract.json | jq -r .abi > crates/evm-contracts/res/TwineSystemStorageContract.json

      - name: Commit changes
        run: |
          BRANCH_NAME="auto-update-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update from workflow"
          git push origin "$BRANCH_NAME"

      - name: Get commit diff
        id: diff
        run: |
          echo '```diff' > changes.txt
          git diff HEAD~1 HEAD >> changes.txt || true
          echo '```' >> changes.txt
          # Store as output for PR body
          CHANGES=$(cat changes.txt)
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.REPO_B_PAT }}
          branch: ${{ github.ref_name }}
          delete-branch: true
          base: main
          title: "evm contract updates from workflow"
          body: |
            This PR was automatically created by a workflow triggered from Repo A.

            **Changes:**
            ${{ steps.diff.outputs.changes }}
          commit-message: "changes for evm contracts"
