name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Cache cargo-udeps
      id: cache-cargo-udeps
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        path: |
          ~/.cargo/bin/cargo-udeps
    - if: ${{ steps.cache-cargo-udeps.outputs.cache-hit != 'true' }}
      name: Install cargo-udeps
      run: cargo install cargo-udeps
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
