name: test-harness

on:
  pull_request:
  push:
    branches: [main]

jobs:
   test-harness:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: Check anvil exists
      run: anvil --version
    - name: Run anvil test
      run: RUST_LOG=info cargo test --package test-harness
